### ISSUE TITLE
Appium java-client 8.5.0 not working with UFTM 

### ISSUE THREAD

**Issue by harkiranjeet** [uftm-cfrd/appium-samples#1]
Hello, 

Even if I am using right username and password, the UFTM is throwing this error.

Capabilities:
//Anonymous Access enabled
            caps.setCapability("uftm:userName", UFTM_SERVER_USERNAME);
            caps.setCapability("uftm:password", UFTM_SERVER_PASSWORD); 
             caps.setCapability("appium:platformName", "Android");
                caps.setCapability("appium:deviceName", "R5CT10KLD3W");
                caps.setCapability("appium:udid", "R5CT10KLD3W");
                caps.setCapability("appium:disableWindowAnimation", "true");
                caps.setCapability("appium:gpsEnabled","true");
                caps.setCapability("appium:noReset", "true");
                caps.setCapability("appium:fullReset", "false");

**Error :** 

org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Unable to parse remote response: <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 401 User provided is not authorized. please check user is active, not expired and exists for tenant for tenant null </title>
</head>
<body><center><hr><i><big>A general error occurred.</big></i><hr/></center>
<center><i><small>Powered by UFT Mobile</small></i></center>

</body>
</html>

**Comment by uftm-cfrd** [comment]
Hello,

I'd like to clarify that the current matter isn't related to the samples, so I'll be closing this inquiry here. It seems the credentials being used might be the issue, particularly the absence of the tenantId capability. Consider creating an execution key as an alternative to using userName and password capabilities.

For additional assistance, feel free to visit the UFT Digital Lab community at https://community.microfocus.com/devops-cloud/uft-digitallab/f/discussions. Alternatively, you can open a Support ticket at https://www.microfocus.com/en-us/support.

Best regards.
